# Nom de notre action automatique
name: Mise à jour quotidienne des offres d'emploi

# Déclencheurs
on:
  workflow_dispatch:
  schedule:
    # Lance le script tous les jours à 6h du matin UTC
    - cron: '0 6 * * *'

# Les tâches à effectuer
jobs:
  build:
    runs-on: ubuntu-latest

    # --- LA CORRECTION EST ICI ---
    # On donne explicitement la permission au bot d'écrire dans le projet
    permissions:
      contents: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Mise en place de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation des dépendances et de Chrome
        run: |
          pip install selenium beautifulsoup4 requests
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Exécution du bot Python
        run: |
          python bot.py

      - name: Commit des nouvelles données
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mise à jour automatique des offres d'emploi"
          file_pattern: 'offres.json'
